"use client";
import {useEffect,useState} from "react"; import Link from "next/link"; import {ActionModal,Badge,PageHead} from "@/components/Portal";
type R=Record<string,string|number|null>;
const meta:Record<string,[string,string,string[]]>={
 "candidate-missing-information":["Candidate Missing Information","Candidate records requiring additional information or authorization.",["Send Candidate Request","Set Follow-Up Date"]],
 "unassigned-searches":["Unassigned Searches","Searches awaiting assignment to an approved vendor or researcher.",["Assign Vendor","Set Due Date"]],
 "verification-follow-up":["Verification Follow-Up","Employment and education outreach actions that are due.",["Log Contact Attempt","Set Next Follow-Up"]],
 "overdue-searches":["Overdue Searches","Searches beyond SLA requiring vendor follow-up or escalation.",["Contact Vendor","Update Completion Date"]],
 "record-review":["Criminal Record Review","Structured identifier comparison requiring a documented human decision.",["Compare Identifiers","Record Review Decision"]],
 "reports-ready-for-qa":["Reports Ready for QA","Complete QA preparation checks before sending reports to review.",["Complete QA Checklist","Send to QA Reviewer"]],
 "reports-ready-to-release":["Reports Ready to Release","QA-approved reports eligible for manual release.",["Review Release Checklist","Release Report"]],
 "billing-exceptions":["Billing Exceptions","Compare vendor costs and client pricing, then resolve or route exceptions.",["Compare Fees","Resolve Exception"]],
 "new-order-review":["New Order Review","Confirm package, authorization, and required search assignments.",["Review Order","Confirm Authorization"]]
};
export default function Queue({params}:{params:Promise<{slug:string}>}){const [slug,setSlug]=useState(""),[data,setData]=useState<R[]>([]),[error,setError]=useState("");useEffect(()=>{params.then(p=>{setSlug(p.slug);fetch(`/api/clearpath/queue?slug=${p.slug}`).then(async r=>{if(!r.ok)throw new Error("Unable to load this queue");return r.json()}).then(setData).catch(e=>setError(e.message))})},[params]);const m=meta[slug]||meta["new-order-review"];return <div className="page"><PageHead eyebrow="WORK QUEUES" title={m[0]} subtitle={m[1]} actions={<Link href="/app/queues" className="btn outline">← All Queues</Link>}/>{error&&<p className="form-error" role="alert">{error}</p>}{slug==="record-review"&&data[0]&&<Comparison item={data[0]}/>}<section className="card table-card"><div className="table-summary"><b>{data.length} open items</b><span>Sorted by priority and age</span><div className="filters-inline"><select disabled title="Priority filtering is not enabled in this demo"><option>All priorities</option></select><select disabled title="Assignee filtering is not enabled in this demo"><option>All assignees</option></select></div></div><table><thead><tr><th>Priority</th><th>Record</th><th>Candidate</th><th>Client / Search Type</th><th>Issue / Jurisdiction</th><th>Status</th><th>Age / Due</th><th>Assigned To</th><th></th></tr></thead><tbody>{data.map((r,i)=><tr key={String(r.record_id||r.id)}><td><Badge tone={i<2?"red":"amber"}>{i<2?"URGENT":"HIGH"}</Badge></td><td><b className="link-blue">{r.record_id}</b></td><td><b>{r.candidate}</b><small>{r.position}</small></td><td><b>{r.client||r.type}</b><small>{r.type}</small></td><td>{r.issue||r.jurisdiction}<small>{r.jurisdiction}</small></td><td><Badge tone="blue">{r.status}</Badge></td><td className={slug==="overdue-searches"?"red-text":""}>{r.aging||r.due_date}</td><td>{r.assigned_to||r.vendor}</td><td><ActionModal label={m[2][0]} title={m[2][1]} entity={String(r.record_id)} fields={slug==="unassigned-searches"?["Approved Vendor","Confirmed Vendor Cost","Due Date"]:slug==="billing-exceptions"?["Corrected Fee","Resolution Status"]:["New Status","Follow-Up Date"]}/></td></tr>)}</tbody></table></section></div>}
function Comparison({item}:{item:R}){return <section className="comparison card"><div className="card-head"><div><h2>Identifier Comparison</h2><p>Compare structured data. Ambiguous identity or reportability decisions must be sent to Compliance Review.</p></div><Badge tone="red">POSSIBLE RECORD</Badge></div><div className="compare-grid"><div><h3>Candidate Information</h3>{[["Full name",item.candidate],["Date of birth","1988-04-16"],["Address","245 Aspen Way, Denver, CO"],["Alias","Olivia M. Bennett"],["Other identifier","SSN ending 1219"]].map(x=><p key={String(x[0])}><small>{x[0]}</small><b>{x[1]}</b></p>)}</div><div><h3>Court Record</h3>{[["Subject name",item.candidate],["Record date of birth","1988-04-16"],["Record address","Denver County, CO"],["Name variation","O. M. Bennett"],["Case / identifier","2024CR01842"]].map(x=><p key={String(x[0])}><small>{x[0]}</small><b>{x[1]}</b></p>)}</div></div><div className="decision-row">{["Confirmed Match","Possible Match","Non-Match","More Research Required","Duplicate Record","Send to Compliance Review"].map(x=><ActionModal key={x} label={x} title={x} entity={String(item.record_id)} fields={["Review Status"]}/>)}</div></section>}
