"use client";

import Link from "next/link";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {LogoutButton} from "@/app/app/PageControls";
import styles from "./candidate.module.css";

type Candidate={name:string;email:string;phone:string;address:string;previousAddress:string};
type Progress={personalStatus:string;addressStatus:string;disclosureStatus:string;authorizationStatus:string;documentStatus:string;currentStep:string;signatureName?:string|null};
type DocumentRecord={id:number;name:string;documentType:string;createdAt:string;sizeBytes:number};
type State={candidate:Candidate;progress:Progress;documents:DocumentRecord[]};
const steps=["Personal Information","Address History","Disclosure Review","Authorization Signature","Document Upload"] as const;

export default function CandidateWorkspace(){
  const [state,setState]=useState<State|null>(null),[active,setActive]=useState<string>("Disclosure Review"),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
  const load=useCallback(async()=>{setLoading(true);try{const response=await fetch("/api/clearpath/candidate/progress",{cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result.error||"Your screening progress could not be loaded.");setState(result);setActive(result.progress.currentStep==="Complete"?"Document Upload":result.progress.currentStep)}catch(caught){setError(caught instanceof Error?caught.message:"Your screening progress could not be loaded.")}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  const completed=useMemo(()=>state?[state.progress.personalStatus,state.progress.addressStatus,state.progress.disclosureStatus,state.progress.authorizationStatus,state.progress.documentStatus].filter(value=>value==="Complete").length:0,[state]);
  async function saveProgress(payload:Record<string,unknown>,message:string){setSaving(true);setError("");setSuccess("");try{const response=await fetch("/api/clearpath/candidate/progress",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(result.error||"Your progress could not be saved.");setState(result);setActive(result.progress.currentStep==="Complete"?"Document Upload":result.progress.currentStep);setSuccess(message)}catch(caught){setError(caught instanceof Error?caught.message:"Your progress could not be saved.")}finally{setSaving(false)}}
  async function personal(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await saveProgress({step:"Personal Information",status:"Complete",personal:{name:form.get("name"),email:form.get("email"),phone:form.get("phone")}},"Personal information saved.")}
  async function address(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await saveProgress({step:"Address History",status:"Complete",address:{address:form.get("address"),previousAddress:form.get("previousAddress")}},"Address history saved.")}
  async function disclosure(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await saveProgress({step:"Disclosure Review",status:"Complete",acknowledged:form.get("acknowledged")==="on"},"Disclosure acknowledged and saved.")}
  async function authorization(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await saveProgress({step:"Authorization Signature",status:"Complete",signatureName:form.get("signatureName")},"Authorization signature recorded.")}
  async function documentUpload(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget,form=new FormData(formElement),file=form.get("document");if(!(file instanceof File)||!file.name){setError("Choose a PDF, PNG, or JPEG document.");return}setSaving(true);setError("");setSuccess("");try{const response=await fetch("/api/clearpath/candidate/documents",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:file.name,documentType:form.get("documentType"),mimeType:file.type,sizeBytes:file.size,storageReference:`recorded://candidate/${encodeURIComponent(file.name)}`})});const result=await response.json();if(!response.ok)throw new Error(result.error||"The document could not be recorded.");formElement.reset();await load();setActive("Document Upload");setSuccess(`${file.name} was recorded securely.`)}catch(caught){setError(caught instanceof Error?caught.message:"The document could not be recorded.")}finally{setSaving(false)}}
  if(loading)return <main className={styles.shell}><div className={styles.loading} role="status">Loading your screening workspace…</div></main>;
  if(!state)return <main className={styles.shell}><div className={styles.errorPanel}><h1>We couldn’t load your screening.</h1><p>{error}</p><button className={styles.primaryButton} onClick={()=>void load()}>Try again</button></div></main>;
  const statuses:Record<string,string>={"Personal Information":state.progress.personalStatus,"Address History":state.progress.addressStatus,"Disclosure Review":state.progress.disclosureStatus,"Authorization Signature":state.progress.authorizationStatus,"Document Upload":state.progress.documentStatus};
  return <main className={styles.shell}>
    <header className={styles.header}><Link href="/" className={styles.brand}><span>CP</span><b>ClearPath Screening</b></Link><div><a href="mailto:candidate-support@clearpath.local">Candidate Support</a><LogoutButton className={styles.secondaryButton}>Sign out</LogoutButton></div></header>
    <section className={styles.hero}><div><span className={styles.eyebrow}>CANDIDATE SCREENING PORTAL</span><h1>Hi {state.candidate.name.split(" ")[0]}, let’s complete your screening.</h1><p>Northstar Health Partners has invited you to complete a background screening. Your saved progress is available whenever you return.</p></div><div className={styles.progressCard}><strong>{completed} of 5 complete</strong><div><span style={{width:`${completed/5*100}%`}}/></div><small>{completed===5?"All candidate steps complete":"Continue with the highlighted step"}</small></div></section>
    <div className={styles.workspace}>
      <nav className={styles.stepNav} aria-label="Screening steps">{steps.map((step,index)=>{const firstIncomplete=steps.findIndex(candidateStep=>statuses[candidateStep]!=="Complete"),locked=firstIncomplete>=0&&index>firstIncomplete&&statuses[step]!=="Complete";return <button type="button" key={step} className={active===step?styles.activeStep:""} disabled={locked} title={locked?"Complete the preceding step first":undefined} onClick={()=>{setActive(step);setError("");setSuccess("")}} aria-current={active===step?"step":undefined}><span className={statuses[step]==="Complete"?styles.stepDone:""}>{statuses[step]==="Complete"?"✓":index+1}</span><span><b>{step}</b><small>{locked?"Locked":statuses[step]}</small></span></button>})}</nav>
      <section className={styles.panel} aria-live="polite">
        {error&&<p className={styles.error} role="alert">{error}</p>}{success&&<p className={styles.success} role="status">✓ {success}</p>}
        {active==="Personal Information"&&<form onSubmit={personal}><FormHead title="Personal information" copy="Confirm the contact information associated with your screening."/><label>Legal name<input name="name" defaultValue={state.candidate.name} required maxLength={160}/></label><div className={styles.twoColumns}><label>Email address<input name="email" type="email" defaultValue={state.candidate.email} required/></label><label>Phone number<input name="phone" defaultValue={state.candidate.phone} required/></label></div><Submit busy={saving}>Save personal information</Submit></form>}
        {active==="Address History"&&<form onSubmit={address}><FormHead title="Address history" copy="Review the addresses used to perform jurisdictional searches."/><label>Current address<input name="address" defaultValue={state.candidate.address} required maxLength={300}/></label><label>Previous address<input name="previousAddress" defaultValue={state.candidate.previousAddress} maxLength={300}/></label><Submit busy={saving}>Save address history</Submit></form>}
        {active==="Disclosure Review"&&<form onSubmit={disclosure}><FormHead title="Disclosure review" copy="Read this disclosure before continuing to authorization."/><div className={styles.disclosure}><h3>Background screening disclosure</h3><p>Northstar Health Partners has requested a consumer report for employment purposes. ClearPath Screening may verify identity, address history, criminal records, employment, education, licenses, and other job-related information included in the screening package.</p><p>This portal contains demonstration data only. Completing this step records your acknowledgment in the ClearPath audit history.</p></div><label className={styles.check}><input name="acknowledged" type="checkbox" required/><span>I acknowledge that I have read and received this disclosure.</span></label><Submit busy={saving}>Accept disclosure and continue</Submit></form>}
        {active==="Authorization Signature"&&<form onSubmit={authorization}><FormHead title="Authorization signature" copy="Type your legal name to record your authorization."/><div className={styles.disclosure}><p>By signing below, I authorize the employer and ClearPath Screening to obtain the employment-purpose background screening described in the disclosure.</p></div><label>Electronic signature<input name="signatureName" defaultValue={state.progress.signatureName||state.candidate.name} required maxLength={160}/><small>Type your full legal name.</small></label><Submit busy={saving}>Sign and continue</Submit></form>}
        {active==="Document Upload"&&<form onSubmit={documentUpload}><FormHead title="Supporting documents" copy="Choose a document to record with this screening. PDF, PNG, and JPEG files are accepted."/><div className={styles.twoColumns}><label>Document type<select name="documentType" defaultValue="Candidate Authorization"><option>Candidate Authorization</option><option>Identity Document</option><option>Supporting Document</option><option>Other</option></select></label><label>Choose document<input name="document" type="file" accept="application/pdf,image/png,image/jpeg" required/></label></div><Submit busy={saving}>Record document</Submit>{state.documents.length>0&&<div className={styles.documentList}><h3>Recorded documents</h3>{state.documents.map(document=><div key={document.id}><span aria-hidden="true">▣</span><span><b>{document.name}</b><small>{document.documentType} · {Math.max(1,Math.round(document.sizeBytes/1024))} KB</small></span><strong>Recorded</strong></div>)}</div>}</form>}
      </section>
    </div>
  </main>
}
function FormHead({title,copy}:{title:string;copy:string}){return <div className={styles.formHead}><span>SECURE CANDIDATE ACTION</span><h2>{title}</h2><p>{copy}</p></div>}
function Submit({busy,children}:{busy:boolean;children:React.ReactNode}){return <div className={styles.formActions}><button className={styles.primaryButton} disabled={busy}>{busy?"Saving…":children}</button></div>}
