"use client";

import {FormEvent,useEffect,useId,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import {Badge} from "@/components/Portal";
import VendorContact from "./VendorContact";
import styles from "./vendors.module.css";

type Vendor={id:string|number;name:string|number|null;coverage:string|number|null;jurisdictions:string|number|null;turnaround:string|number|null;cost:string|number|null;quality:string|number|null;preferred:string|number|boolean|null;status:string|number|null;contact:string|number|null};
type EditState={mode:"create"}|{mode:"edit";vendor:Vendor};

export default function VendorWorkspace({initialVendors,canManage}:{initialVendors:Vendor[];canManage:boolean}){
  const router=useRouter(),[vendors,setVendors]=useState(initialVendors),[editing,setEditing]=useState<EditState|null>(null),[saving,setSaving]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
  const titleId=useId(),triggerRef=useRef<HTMLButtonElement>(null);
  useEffect(()=>setVendors(initialVendors),[initialVendors]);
  useEffect(()=>{if(!editing)return;const escape=(event:KeyboardEvent)=>{if(event.key==="Escape"&&!saving)close()};document.addEventListener("keydown",escape);return()=>document.removeEventListener("keydown",escape)},[editing,saving]);
  function close(){if(saving)return;setEditing(null);setError("");triggerRef.current?.focus()}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!editing)return;const form=new FormData(event.currentTarget),payload={name:String(form.get("name")||"").trim(),coverage:String(form.get("coverage")||"").trim(),jurisdictions:String(form.get("jurisdictions")||"").trim(),turnaround:String(form.get("turnaround")||"").trim(),cost:Number(form.get("cost")),quality:Number(form.get("quality")),preferred:form.get("preferred")==="on",status:String(form.get("status")),contact:String(form.get("contact")||"").trim(),...(editing.mode==="edit"?{note:String(form.get("note")||"").trim()}:{})};setSaving(true);setError("");setSuccess("");try{const endpoint=editing.mode==="edit"?`/api/clearpath/vendors/${editing.vendor.id}`:"/api/clearpath/vendors",response=await fetch(endpoint,{method:editing.mode==="edit"?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),result=await response.json();if(!response.ok)throw new Error(result.error||"The vendor could not be saved.");setVendors(current=>editing.mode==="edit"?current.map(vendor=>String(vendor.id)===String(result.vendor.id)?result.vendor:vendor):[result.vendor,...current]);setSuccess(`${result.vendor.name} was ${editing.mode==="edit"?"updated":"added"}.`);setEditing(null);router.refresh();triggerRef.current?.focus()}catch(caught){setError(caught instanceof Error?caught.message:"The vendor could not be saved.")}finally{setSaving(false)}}
  return <div className={`page ${styles.page}`}><div className={styles.heading}><div><span>RESEARCH NETWORK</span><h1>Vendor Directory</h1><p>Approved screening and court-research partners, service coverage, quality, and communication history.</p></div>{canManage&&<button ref={triggerRef} className={styles.primaryButton} onClick={()=>{setEditing({mode:"create"});setError("");setSuccess("")}}>+ Add vendor</button>}</div>
    {success&&<p className={styles.success} role="status">✓ {success}</p>}
    <div className={styles.summary}><div><strong>{vendors.length}</strong><span>Approved partners</span></div><div><strong>{vendors.filter(vendor=>Number(vendor.preferred)===1||vendor.preferred===true).length}</strong><span>Preferred vendors</span></div><div><strong>{Math.round(vendors.reduce((sum,vendor)=>sum+Number(vendor.quality||0),0)/Math.max(1,vendors.length))}%</strong><span>Average quality</span></div></div>
    <div className={styles.grid}>{vendors.map(vendor=><article className={styles.vendorCard} key={String(vendor.id)}><div className={styles.vendorHead}><span className={styles.initials}>{String(vendor.name).split(" ").map(part=>part[0]).join("").slice(0,2)}</span><div><Badge tone={vendor.status==="Active"?"green":"gray"}>{vendor.status}</Badge>{(Number(vendor.preferred)===1||vendor.preferred===true)&&<Badge tone="blue">★ Preferred</Badge>}</div></div><h2>{vendor.name}</h2><p className={styles.coverage}>{vendor.coverage}</p><dl><div><dt>Jurisdictions</dt><dd>{vendor.jurisdictions}</dd></div><div><dt>Average turnaround</dt><dd>{vendor.turnaround}</dd></div><div><dt>Standard cost</dt><dd>${Number(vendor.cost).toFixed(2)}</dd></div><div><dt>Quality score</dt><dd><strong>{vendor.quality}%</strong></dd></div><div><dt>Contact</dt><dd>{vendor.contact}</dd></div></dl>{canManage&&<button type="button" className={styles.editButton} onClick={()=>{setEditing({mode:"edit",vendor});setError("");setSuccess("")}}>Edit vendor</button>}<VendorContact vendorId={Number(vendor.id)} vendorName={String(vendor.name)}/></article>)}</div>
    {editing&&<div className={styles.backdrop} onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><section className={styles.modal} role="dialog" aria-modal="true" aria-labelledby={titleId}><div className={styles.modalHead}><div><span>VENDOR MANAGEMENT</span><h2 id={titleId}>{editing.mode==="create"?"Add an approved vendor":`Edit ${editing.vendor.name}`}</h2><p>Maintain the operational details used for search assignment.</p></div><button type="button" onClick={close} aria-label="Close vendor form" disabled={saving}>×</button></div><VendorForm key={editing.mode==="edit"?String(editing.vendor.id):"create"} vendor={editing.mode==="edit"?editing.vendor:undefined} onSubmit={submit} saving={saving} error={error} onCancel={close}/></section></div>}
  </div>
}
function VendorForm({vendor,onSubmit,saving,error,onCancel}:{vendor?:Vendor;onSubmit:(event:FormEvent<HTMLFormElement>)=>void;saving:boolean;error:string;onCancel:()=>void}){return <form onSubmit={onSubmit}><div className={styles.twoColumns}><label>Vendor name<input autoFocus name="name" defaultValue={String(vendor?.name||"")} required maxLength={160}/></label><label>Contact email<input name="contact" type="email" defaultValue={String(vendor?.contact||"")} required/></label><label>Service coverage<input name="coverage" defaultValue={String(vendor?.coverage||"")} required maxLength={300}/></label><label>Jurisdictions<input name="jurisdictions" defaultValue={String(vendor?.jurisdictions||"")} required maxLength={300}/></label><label>Average turnaround<input name="turnaround" defaultValue={String(vendor?.turnaround||"")} placeholder="2.0 days" required maxLength={100}/></label><label>Status<select name="status" defaultValue={String(vendor?.status||"Active")}><option>Active</option><option>Inactive</option></select></label><label>Standard cost<input name="cost" type="number" min="0" step="0.01" defaultValue={String(vendor?.cost??"")} required/></label><label>Quality score<input name="quality" type="number" min="0" max="100" step="1" defaultValue={String(vendor?.quality??"")} required/></label></div><label className={styles.check}><input name="preferred" type="checkbox" defaultChecked={Number(vendor?.preferred)===1||vendor?.preferred===true}/><span>Preferred vendor for matching coverage</span></label>{vendor&&<label>Change note <span>(optional)</span><textarea name="note" rows={3} maxLength={2000} placeholder="Document why vendor details changed."/></label>}{error&&<p className={styles.error} role="alert">{error}</p>}<div className={styles.actions}><button type="button" className={styles.secondaryButton} onClick={onCancel} disabled={saving}>Cancel</button><button className={styles.primaryButton} disabled={saving}>{saving?"Saving…":vendor?"Save vendor":"Add vendor"}</button></div></form>}
