"use client";

import Link from "next/link";
import {FormEvent,useCallback,useEffect,useId,useMemo,useRef,useState} from "react";
import {LogoutButton} from "@/app/app/PageControls";
import styles from "./client.module.css";

type Order={orderId:string;candidate:string;position:string;package:string;orderDate:string;targetDate:string;status:string;aging:number};
type State={client:{id:number;name:string};orders:Order[]};

export default function ClientWorkspace(){
  const [state,setState]=useState<State|null>(null),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
  const titleId=useId(),triggerRef=useRef<HTMLButtonElement>(null),nameRef=useRef<HTMLInputElement>(null);
  const load=useCallback(async()=>{setLoading(true);try{const response=await fetch("/api/clearpath/client/orders",{cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result.error||"Client orders could not be loaded.");setState(result);setError("")}catch(caught){setError(caught instanceof Error?caught.message:"Client orders could not be loaded.")}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  useEffect(()=>{if(!open)return;nameRef.current?.focus();const escape=(event:KeyboardEvent)=>{if(event.key==="Escape"&&!saving)close()};document.addEventListener("keydown",escape);return()=>document.removeEventListener("keydown",escape)},[open,saving]);
  const metrics=useMemo(()=>{const orders=state?.orders||[];return {active:orders.filter(order=>order.status!=="Complete"&&order.status!=="Cancelled").length,action:orders.filter(order=>order.status.includes("Action Required")).length,ready:orders.filter(order=>order.status==="Complete").length,pending:orders.filter(order=>order.status.includes("Candidate")).length}},[state]);
  function close(){if(saving)return;setOpen(false);setError("");triggerRef.current?.focus()}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget,form=new FormData(formElement);setSaving(true);setError("");setSuccess("");const payload={candidate:{name:form.get("candidateName"),dob:form.get("dob"),ssn:form.get("ssn"),email:form.get("candidateEmail"),phone:form.get("phone"),address:form.get("address"),previousAddress:form.get("previousAddress"),aliases:form.get("aliases")},position:form.get("position"),package:form.get("package"),targetDate:form.get("targetDate"),priority:form.get("priority"),hiringLocation:form.get("hiringLocation"),recruiter:form.get("recruiter")};try{const response=await fetch("/api/clearpath/client/orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(result.error||"The screening order could not be submitted.");formElement.reset();setOpen(false);await load();setSuccess(`Order ${result.order.orderId} was submitted for ${result.order.candidate}.`);triggerRef.current?.focus()}catch(caught){setError(caught instanceof Error?caught.message:"The screening order could not be submitted.")}finally{setSaving(false)}}
  return <main className={styles.shell}>
    <header className={styles.header}><Link href="/" className={styles.brand}><span>CP</span><b>ClearPath Screening</b></Link><nav aria-label="Client navigation"><a href="#dashboard">Dashboard</a><a href="#orders">Orders</a><a href="mailto:support@clearpath.local">Support</a></nav><LogoutButton className={styles.signOut}>Log out</LogoutButton></header>
    <section className={styles.hero} id="dashboard"><div><span>CLIENT PORTAL</span><h1>{state?`Welcome, ${state.client.name}`:"Welcome to ClearPath"}</h1><p>Submit screening orders, monitor progress, and see when reports are ready for your team.</p></div><button ref={triggerRef} className={styles.primaryButton} onClick={()=>{setOpen(true);setError("");setSuccess("")}}>+ Submit screening order</button></section>
    <section className={styles.content}>
      {error&&!open&&<p className={styles.error} role="alert">{error}</p>}{success&&<p className={styles.success} role="status">✓ {success}</p>}
      <div className={styles.metrics} aria-label="Client order summary"><Metric value={metrics.active} label="Active orders" detail="Currently screening"/><Metric value={metrics.action} label="Action required" detail="Waiting on your team" tone="amber"/><Metric value={metrics.ready} label="Reports ready" detail="Completed orders" tone="green"/><Metric value={metrics.pending} label="Candidate pending" detail="Candidate steps open"/></div>
      <section className={styles.orderCard} id="orders"><div className={styles.cardHead}><div><span>ORDER ACTIVITY</span><h2>Screening orders</h2><p>Only orders for your organization are shown.</p></div><strong>{state?.orders.length||0} total</strong></div>
        {loading?<div className={styles.empty} role="status">Loading client orders…</div>:state?.orders.length?<div className={styles.tableWrap}><table><thead><tr><th>Order</th><th>Candidate</th><th>Position</th><th>Package</th><th>Submitted</th><th>Target</th><th>Status</th></tr></thead><tbody>{state.orders.map(order=><tr key={order.orderId}><td><b>{order.orderId}</b></td><td>{order.candidate}</td><td>{order.position}</td><td>{order.package}</td><td>{order.orderDate}</td><td>{order.targetDate}</td><td><span className={`${styles.status} ${order.status==="Complete"?styles.statusGreen:order.status.includes("Action")?styles.statusAmber:""}`}>{order.status}</span></td></tr>)}</tbody></table></div>:<div className={styles.empty}>No orders have been submitted yet.</div>}
      </section>
    </section>
    {open&&<div className={styles.modalBackdrop} onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><section className={styles.modal} role="dialog" aria-modal="true" aria-labelledby={titleId}><div className={styles.modalHead}><div><span>NEW SCREENING ORDER</span><h2 id={titleId}>Submit an order</h2><p>The order will be securely assigned to {state?.client.name||"your organization"}.</p></div><button type="button" onClick={close} aria-label="Close order form" disabled={saving}>×</button></div><form onSubmit={submit}>
      <fieldset><legend>Candidate information</legend><div className={styles.twoColumns}><label>Legal name<input ref={nameRef} name="candidateName" required maxLength={160}/></label><label>Email address<input name="candidateEmail" type="email" required/></label><label>Date of birth<input name="dob" type="date" required/></label><label>SSN last four<input name="ssn" inputMode="numeric" pattern="[0-9]{4}" maxLength={4} placeholder="1234" required/></label><label>Phone number<input name="phone" required maxLength={40}/></label><label>Aliases <span>(optional)</span><input name="aliases" maxLength={300}/></label></div><label>Current address<input name="address" required maxLength={300}/></label><label>Previous address <span>(optional)</span><input name="previousAddress" maxLength={300}/></label></fieldset>
      <fieldset><legend>Order details</legend><div className={styles.twoColumns}><label>Position<input name="position" required maxLength={160}/></label><label>Screening package<select name="package" defaultValue="Standard"><option>Basic</option><option>Standard</option><option>Professional</option><option>Healthcare</option></select></label><label>Hiring location<input name="hiringLocation" defaultValue="Denver, CO" required maxLength={200}/></label><label>Recruiter<input name="recruiter" required maxLength={160}/></label><label>Target completion<input name="targetDate" type="date" required/></label><label>Priority<select name="priority" defaultValue="Normal"><option>Normal</option><option>High</option><option>Urgent</option></select></label></div></fieldset>
      {error&&<p className={styles.error} role="alert">{error}</p>}<div className={styles.modalActions}><button type="button" className={styles.secondaryButton} onClick={close} disabled={saving}>Cancel</button><button className={styles.primaryButton} disabled={saving}>{saving?"Submitting…":"Submit order"}</button></div>
    </form></section></div>}
  </main>
}
function Metric({value,label,detail,tone="blue"}:{value:number;label:string;detail:string;tone?:string}){return <article className={`${styles.metric} ${tone==="amber"?styles.metricAmber:tone==="green"?styles.metricGreen:""}`}><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>}
