"use client";
import Link from "next/link"; import {usePathname,useRouter} from "next/navigation"; import {useState} from "react";
const nav=["Dashboard","Orders","Work Queues","Candidates","Searches","Quality Review","Clients","Vendors","Billing","Reports","Audit Log","Administration"];
const paths:Record<string,string>={Dashboard:"dashboard",Orders:"orders","Work Queues":"queues",Candidates:"candidates",Searches:"searches","Quality Review":"quality-review",Clients:"clients",Vendors:"vendors",Billing:"billing",Reports:"reports","Audit Log":"audit-log",Administration:"admin"};
const icons=["▦","▤","☷","♙","⌕","✓","▣","◇","$","▥","↻","⚙"];
export function Portal({children,user={name:"Taylor Reed",role:"Operations Specialist"}}:{children:React.ReactNode,user?:{name:string,role:string}}){const p=usePathname();return <div className="portal"><aside><Link href="/" className="brand inverse"><span className="brand-mark">CP</span><span>ClearPath <b>Screening</b><small>OPERATIONS PORTAL</small></span></Link><nav>{nav.map((x,i)=><Link className={p.includes(`/app/${paths[x]}`)?"active":""} href={`/app/${paths[x]}`} key={x}><span>{icons[i]}</span>{x}{x==="Work Queues"&&<b className="nav-count">43</b>}</Link>)}</nav><div className="system"><span className="pulse"></span><div><b>All systems operational</b><small>Demo environment</small></div></div><div className="side-user"><span>{user.name.split(" ").map(x=>x[0]).join("")}</span><div><b>{user.name}</b><small>{user.role}</small></div><b>⋮</b></div></aside><main className="portal-main"><header><div className="global-search">⌕ <input placeholder="Search orders, candidates, searches..."/><kbd>⌘ K</kbd></div><div className="header-actions"><span className="date">Sunday, July 12, 2026</span><button>?</button><button>♢<i>3</i></button></div></header>{children}</main></div>}
export function PageHead({eyebrow,title,subtitle,actions}:{eyebrow:string,title:string,subtitle:string,actions?:React.ReactNode}){return <div className="page-head"><div><p className="kicker">{eyebrow}</p><h1>{title}</h1><p>{subtitle}</p></div>{actions&&<div className="page-actions">{actions}</div>}</div>}
export function Badge({children,tone="gray"}:{children:React.ReactNode,tone?:string}){return <span className={`badge ${tone}`}>{children}</span>}
export function ActionModal({label="Open",title,entity,fields=[]}:{label?:string,title:string,entity:string,fields?:string[]}){const [open,setOpen]=useState(false),[saving,setSaving]=useState(false),[values,setValues]=useState<Record<string,string>>({}),[note,setNote]=useState(""),[error,setError]=useState("");function setField(name:string,value:string){setValues(current=>({...current,[name]:value}))}async function save(){setSaving(true);setError("");try{const res=await fetch("/api/clearpath/action",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:title,entityId:entity,values,note})});const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body.error||"Unable to save changes");setOpen(false);setValues({});setNote("");location.reload()}catch(e){setError(e instanceof Error?e.message:"Unable to save changes")}finally{setSaving(false)}}return <><button className="table-action" onClick={()=>{setError("");setOpen(true)}}>{label} →</button>{open&&<div className="modal-bg"><div className="modal"><div className="modal-head"><div><p className="kicker">MANUAL OPERATION</p><h2>{title}</h2><p>{entity}</p></div><button type="button" aria-label="Close" onClick={()=>setOpen(false)}>×</button></div>{fields.map(f=><label key={f}>{f}{f.includes("Status")?<select value={values[f]||""} onChange={e=>setField(f,e.target.value)}><option value="">Select status</option><option>In Progress</option><option>Awaiting Vendor</option><option>Quality Review</option><option>Completed</option><option>Resolved</option><option>Pending Review</option><option>Approved</option></select>:<input value={values[f]||""} onChange={e=>setField(f,e.target.value)} type={f.includes("Date")?"date":f.includes("Cost")||f.includes("Fee")?"number":"text"} min={f.includes("Cost")||f.includes("Fee")?"0":undefined} step={f.includes("Cost")||f.includes("Fee")?"0.01":undefined} placeholder={`Enter ${f.toLowerCase()}`}/>}</label>)}<label>Internal note<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Document the action taken and relevant context"></textarea></label>{error&&<p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="btn outline" onClick={()=>setOpen(false)}>Cancel</button><button type="button" className="btn primary" onClick={save} disabled={saving}>{saving?"Saving…":"Save Changes"}</button></div></div></div>}</>}
